import type { NextPage } from 'next';
import Head from 'next/head';
import LoginButton from '../components/LoginButton';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hello World</h1>

        <div>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi
            consequatur delectus ducimus ex excepturi fuga ipsam natus nisi rem
            sunt.
          </p>
          <LoginButton />
        </div>
      </main>
    </div>
  );
};

export default Home;
